version: "3.9"

services:
  db:
    image: postgres:15
    container_name: lectureflow-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lectureflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dbase:/docker-entrypoint-initdb.d


  redis:
    image: redis:7
    container_name: lectureflow-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: lectureflow-api
    ports:
      - "4000:4000"
    environment:
      PORT: 4000

      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lectureflow

      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/uploads

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: lectureflow-worker
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lectureflow

      REDIS_HOST: redis
      REDIS_PORT: 6379

      WHISPER_MODEL: tiny
    depends_on:
      - db
      - redis
    volumes:
      - ./uploads:/uploads

volumes:
  postgres_data:
